const { GoogleGenerativeAI } = require('@google/generative-ai');

// Safely initialize the Gemini client
const apiKey = process.env.GEMINI_API_KEY;
let genAI = null;

if (apiKey) {
  genAI = new GoogleGenerativeAI(apiKey);
} else {
  console.warn('WARNING: GEMINI_API_KEY is not set in environment variables.');
}

/**
 * Sends a structured prompt to the Gemini model and retrieves the generated rewrite.
 * 
 * @param {string} prompt - The fully constructed prompt string to send to the AI.
 * @returns {Promise<string>} The rewritten text generated by the AI.
 * @throws {Error} A clean, application-level error if the generation fails.
 */
const generateRewrite = async (prompt) => {
  if (!genAI) {
    console.error('Internal Error: GoogleGenerativeAI client is not initialized due to missing API key.');
    throw new Error('AI service is currently unavailable. Please try again later.');
  }

  try {
    // We use gemini-2.5-flash as it is fast, efficient, and well-suited for text generation
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    // Call the Gemini API
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const generatedText = response.text();

    // Handle edge case where the AI returns an unexpectedly empty response
    if (!generatedText || generatedText.trim() === '') {
      console.error('Internal Error: Gemini API returned an empty text string.');
      throw new Error('The AI failed to generate a rewrite. Please try again.');
    }

    return generatedText.trim();

  } catch (error) {
    // Log the raw error securely on the server-side only
    console.error('Gemini API Generation Error:', error);
    
    // Do NOT expose raw provider errors to the client. Throw a generic clean error instead.
    throw new Error('An error occurred while processing your request. Please try again.');
  }
};

module.exports = {
  generateRewrite
};
